"""
FAKE NEWS DETECTION - Model Training Script
--------------------------------------------
Steps (viva mein yehi flow bolna hai):
1. Load dataset (Kaggle True.csv/Fake.csv agar available hai, warna sample dataset)
2. Text cleaning (lowercase, remove punctuation, remove stopwords)
3. Train-test split
4. TF-IDF vectorization (text ko numbers mein convert karna)
5. Train 2 models: PassiveAggressiveClassifier & Logistic Regression
6. Evaluate: accuracy, precision, recall, f1, confusion matrix
7. Save best model + vectorizer using pickle (for use in Streamlit app)
"""

import os
import re
import string
import pickle
import pandas as pd
import time
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import PassiveAggressiveClassifier, LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report, confusion_matrix

# ---------- STEP 1: LOAD DATA ----------
def load_data():
    if os.path.exists("True.csv") and os.path.exists("Fake.csv"):
        # Real Kaggle dataset format
        true_df = pd.read_csv("True.csv")
        fake_df = pd.read_csv("Fake.csv")
        true_df["label"] = "REAL"
        fake_df["label"] = "FAKE"
        df = pd.concat([true_df, fake_df], ignore_index=True)
        # Kaggle dataset has 'title' and 'text' columns -> combine them
        if "title" in df.columns:
            df["text"] = df["title"].fillna("") + " " + df["text"].fillna("")
        print(f"Loaded REAL Kaggle dataset: {len(df)} rows")
    else:
        # Fallback: sample dataset (generated by make_sample_data.py)
        if not os.path.exists("news_dataset.csv"):
            raise FileNotFoundError(
                "Koi dataset nahi mila! Pehle 'python make_sample_data.py' chalao, "
                "ya True.csv/Fake.csv is folder mein daalo (Kaggle se download karke)."
            )
        df = pd.read_csv("news_dataset.csv")
        print(f"Loaded sample dataset: {len(df)} rows")

    df = df.dropna(subset=["text", "label"])
    df = df.drop_duplicates(subset=["text"])  # duplicate articles se accuracy fake badh jaati hai
    df = df.sample(frac=1, random_state=42).reset_index(drop=True)  # shuffle
    return df


# ---------- STEP 2: TEXT CLEANING ----------
def clean_text(text):
    text = str(text)
    # Kaggle dataset ka "shortcut" hatao: real news mein "WASHINGTON (Reuters) -" jaisa tag hota hai
    text = re.sub(r"^.{0,80}?\(reuters\)\s*-?\s*", "", text, flags=re.IGNORECASE)
    text = re.sub(r"\b(reuters|getty images|featured image|21st century wire|21wire)\b", " ", text, flags=re.IGNORECASE)
    text = text.lower()                          # lowercase
    text = re.sub(r"https?://\S+|www\.\S+", "", text)  # remove URLs
    text = re.sub(r"<.*?>", "", text)                  # remove HTML tags
    text = re.sub(f"[{re.escape(string.punctuation)}]", "", text)  # remove punctuation
    text = re.sub(r"\d+", "", text)                    # remove numbers
    text = re.sub(r"\s+", " ", text).strip()           # remove extra spaces
    return text


def main():
    df = load_data()

    print("\nCleaning text...")
    df["clean_text"] = df["text"].apply(clean_text)

    # ---------- STEP 3: TRAIN-TEST SPLIT ----------
    X_train, X_test, y_train, y_test = train_test_split(
        df["clean_text"], df["label"], test_size=0.2, random_state=42, stratify=df["label"]
    )
    print(f"Train size: {len(X_train)}, Test size: {len(X_test)}")

    # ---------- STEP 4: TF-IDF VECTORIZATION ----------
    # TF-IDF = Term Frequency-Inverse Document Frequency
    # Har word ko ek numeric weight deta hai based on:
    #  - kitni baar word document mein aaya (TF)
    #  - kitna rare/common word hai across all documents (IDF)
    vectorizer = TfidfVectorizer(stop_words="english", max_df=0.7, ngram_range=(1, 2))
    X_train_tfidf = vectorizer.fit_transform(X_train)
    X_test_tfidf = vectorizer.transform(X_test)

    # ---------- STEP 5: TRAIN MULTIPLE MODELS (classical ML comparison) ----------
    # 5 classifiers trained on the SAME TF-IDF features, so results are directly comparable.
    models = {
        "Logistic Regression": LogisticRegression(max_iter=1000),
        "Multinomial Naive Bayes": MultinomialNB(),
        "Support Vector Machine (Linear SVC)": LinearSVC(max_iter=2000),
        "Random Forest": RandomForestClassifier(n_estimators=200, random_state=42),
        "Passive Aggressive Classifier": PassiveAggressiveClassifier(max_iter=100),
    }

    results = []  # for the comparison table
    trained_models = {}

    for name, model in models.items():
        print(f"\nTraining {name}...")
        start = time.time()
        model.fit(X_train_tfidf, y_train)
        train_time = time.time() - start

        start = time.time()
        preds = model.predict(X_test_tfidf)
        inference_time = (time.time() - start) / len(y_test) * 1000  # ms per sample

        acc = accuracy_score(y_test, preds)
        prec = precision_score(y_test, preds, pos_label="FAKE")
        rec = recall_score(y_test, preds, pos_label="FAKE")
        f1 = f1_score(y_test, preds, pos_label="FAKE")

        print(f"===== {name} =====")
        print(f"Accuracy: {acc*100:.2f}%  |  Train time: {train_time:.2f}s  |  Inference: {inference_time:.3f} ms/sample")
        print(classification_report(y_test, preds))
        print("Confusion Matrix:\n", confusion_matrix(y_test, preds))

        results.append({
            "Model": name, "Accuracy": acc, "Precision": prec, "Recall": rec,
            "F1-score": f1, "Train Time (s)": train_time, "Inference (ms/sample)": inference_time
        })
        trained_models[name] = model

    # ---------- STEP 6: COMPARISON TABLE (accuracy-vs-latency trade-off) ----------
    results_df = pd.DataFrame(results).sort_values("Accuracy", ascending=False)
    print("\n\n================ MODEL COMPARISON TABLE ================")
    print(results_df.to_string(index=False))
    results_df.to_csv("model_comparison.csv", index=False)
    print("\nComparison table saved to model_comparison.csv")

    # Pick the best model by accuracy (ties broken by lower inference time)
    best_name = results_df.iloc[0]["Model"]
    final_model = trained_models[best_name]
    print(f"\nBest model selected for deployment: {best_name}")
    if not hasattr(final_model, "predict_proba"):
        print("Note: this model has no predict_proba (e.g. SVM) -- app.py falls back to "
              "decision_function-based confidence for it.")

    # ---------- STEP 7: SAVE MODEL + VECTORIZER ----------
    with open("model.pkl", "wb") as f:
        pickle.dump(final_model, f)
    with open("vectorizer.pkl", "wb") as f:
        pickle.dump(vectorizer, f)

    print("\nModel aur vectorizer save ho gaye: model.pkl, vectorizer.pkl")


if __name__ == "__main__":
    main()
